/*
 * boot_anim.c — Dignity OS startup animation sequencer.
 * Concept firmware for the fictional Dignity set-top box.
 *
 * The video side never keeps its own time: every call to boot_anim_step()
 * reads the APU DAC sample counter and fires the keyframes that counter
 * has passed. If a frame is dropped, the next step emits the missed
 * keyframes in order, so the picture snaps back onto the soundtrack
 * instead of drifting behind it.
 */

#include "boot_anim.h"

/* hw_audio.s */
extern void     apu_init(void);
extern void     apu_counter_reset(void);
extern uint32_t apu_sample_count(void);
extern void     apu_voice_on(uint8_t voice, uint16_t hz,
                             uint8_t level, uint16_t dur_ms);

/* Keyframe table generated by tools/mktimeline from boot_timeline.xml.
 * Kept sorted by sample; sentinel BOOT_OP_NONE terminates. */
static const boot_key_t k_video[] = {
    {      0, BOOT_OP_CRT_FLASH, 0 },
    {  17600, BOOT_OP_LETTER,    0 },   /* D  + pluck D4  */
    {  21760, BOOT_OP_LETTER,    1 },   /* I  + pluck E4  */
    {  25920, BOOT_OP_LETTER,    2 },   /* G  + pluck F#4 */
    {  30080, BOOT_OP_LETTER,    3 },   /* N  + pluck A4  */
    {  34240, BOOT_OP_LETTER,    4 },   /* I  + pluck B4  */
    {  38400, BOOT_OP_LETTER,    5 },   /* T  + pluck D5  */
    {  42560, BOOT_OP_LETTER,    6 },   /* Y  + pluck E5  */
    {  54400, BOOT_OP_SWEEP,     0 },   /* red sweep + chord swell */
    {  75200, BOOT_OP_TAGLINE,   0 },   /* tagline + sparkle dings */
    { 105600, BOOT_OP_OSLINE,    0 },
    { 150400, BOOT_OP_DONE,      0 },
    {      0, BOOT_OP_NONE,      0 }
};

/* Jingle voice schedule (also from boot_timeline.xml). The APU applies
 * the pluck envelope in hardware; we only start voices on time. */
typedef struct {
    uint32_t sample;
    uint8_t  voice;
    uint16_t hz;
    uint8_t  level;
    uint16_t dur_ms;
} boot_note_t;

static const boot_note_t k_notes[] = {
    {      0, 0,   58, 13, 2200 },      /* power hum          */
    {  17600, 1,  294, 56,  500 },
    {  21760, 2,  330, 56,  500 },
    {  25920, 3,  370, 56,  500 },
    {  30080, 1,  440, 56,  500 },
    {  34240, 2,  494, 56,  500 },
    {  38400, 3,  587, 56,  500 },
    {  42560, 1,  659, 56,  500 },
    {  54400, 0,  147, 23, 1900 },      /* chord root D3      */
    {  54400, 2,  220, 23, 1900 },      /* A3                 */
    {  54400, 3,  294, 23, 1900 },      /* D4                 */
    {  75200, 1, 1175, 31,  900 },      /* sparkle D6         */
    {  77440, 2, 1568, 26, 1100 },      /* sparkle G6         */
    {      0, 0,    0,  0,    0 }
};

static uint16_t s_next_key;
static uint16_t s_next_note;
static uint8_t  s_done;

void boot_anim_start(void) {
    apu_init();
    apu_counter_reset();
    s_next_key  = 0;
    s_next_note = 0;
    s_done      = 0;
}

int boot_anim_step(void (*emit)(boot_op_t op, uint8_t arg)) {
    uint32_t now;

    if (s_done)
        return 1;

    now = apu_sample_count();

    /* Start every jingle voice whose timestamp has arrived. Notes are
     * started from the video loop rather than an ISR so a single table
     * drives both halves of the timeline. */
    while (k_notes[s_next_note].hz != 0 &&
           now >= k_notes[s_next_note].sample) {
        const boot_note_t *n = &k_notes[s_next_note++];
        apu_voice_on(n->voice, n->hz, n->level, n->dur_ms);
    }

    /* Fire every video keyframe the DAC counter has passed. */
    while (k_video[s_next_key].op != BOOT_OP_NONE &&
           now >= k_video[s_next_key].sample) {
        const boot_key_t *k = &k_video[s_next_key++];
        emit(k->op, k->arg);
        if (k->op == BOOT_OP_DONE)
            s_done = 1;
    }

    return s_done;
}
